---
name: Build and run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Execute Gradle build for all subfolders
      - name: Gradle Build
        run: |
          for dir in */ ; do
            if [[ -f "$dir/build.gradle.kts" || -f "$dir/build.gradle" ]]; then
              echo "Building $dir"
              (cd $dir ; ./gradlew clean build)
            fi
          done
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./build/jacoco
          verbose: true # optional (default = false)

      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: Test report
          path: build/reports/tests/test
